#!/bin/bash

function usage {
    echo "Usage: $0 up|down|logs|ps";
    exit 1;
}

BASEDIR="${HOME}/.es";
mkdir -p "${BASEDIR}";
COMPOSE_FILE="${BASEDIR}/docker-compose.yml";

cat << EOF > "$COMPOSE_FILE"
version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:6.8.1
    ports:
     - "127.0.0.1:9200:9200"
     - "127.0.0.1:9300:9300"
    volumes:
     - "./usr/share/elasticsearch/data:/usr/share/elasticsearch/data"
  cerebro:
    image: "yannart/cerebro"
    ports:
     - "127.0.0.1:9000:9000"

EOF

case $1 in
	down )
		docker-compose -f "$COMPOSE_FILE" down;
		exit $?;
		;;
	up )
	    set -e
	    docker-compose -f "$COMPOSE_FILE" up --no-recreate -d

	    x=300;
	    sp="/-\|"
	    until [[ $(curl -o /dev/null -sw "%{http_code}" http://localhost:9000/) == "200" && $(curl -o /dev/null -sw "%{http_code}" http://localhost:9200/) == "200" && $x -gt 0 ]]
	    do
	    	printf "\b${sp:i++%${#sp}:1}"
	    	sleep .1
	    	((x-=1))
	    done

	    printf "\b";

	    open 'http://localhost:9000/#/overview?host=http:%2F%2Felasticsearch:9200';
	    exit $?
	    ;;
	logs )
		shift;
	    docker-compose -f "$COMPOSE_FILE" logs $@;
	    exit 0;
		;;
	ps )
		shift;
	    docker-compose -f "$COMPOSE_FILE" ps $@;
	    exit $?;
		;;
	* )
		usage;
		;;
esac




